# Language
language: cpp

# Blacklist
branches:
  except:
      - gh-pages

# Environment variables
env:
  global:
    - DOXYFILE: $TRAVIS_BUILD_DIR/kommandos/DOXYFILE

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Setup SSH
script:
- bash $TRAVIS_BUILD_DIR/kommandos/generateDocumentationAndDeploy.sh
