# Language
language: cpp

# Branches
branches:
  only:
      - comment

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Setup GitHub credentials and generate documentation
script:
- bash $TRAVIS_BUILD_DIR/kommandos/generateDocumentationAndDeploy.sh
