# Language
language: cpp

# Blacklist
branches:
  except:
      - gh-pages

# Environment variables
env:
  global:
    - DOXYFILE: $TRAVIS_BUILD_DIR/kommandos/DOXYFILE

# Decrypt SSH
before_install:
- sudo apt-get update
- sudo apt-get install doxygen
- sudo apt-get install doxygen-gui
- sudo apt-get install graphviz

# Setup SSH
script:
- bash config/generateDocumentationAndDeploy.sh
