GameOverState.cpp File Reference
#include `GameOverState.h`
*
#include <irrlicht.h>
*
Functions
vector3df objScale (100, 100, 100)
vector3df objPosition (-25, 0, 20)
vector3df objRotate (0,-90, 0)
Variables
const path gameOver = `../media/Models/arena/GameOverScreen.3ds`
Function Documentation
vector3df objPosition (- 25, 0 , 20)
Referenced by GameOverState::ShowGameOver().
vector3df objRotate (0 , - 90, 0)
Referenced by GameOverState::ShowGameOver().
vector3df objScale (100 , 100 , 100)
Referenced by GameOverState::ShowGameOver().
Variable Documentation
const path gameOver = `../media/Models/arena/GameOverScreen.3ds`
Referenced by GameOverState::ShowGameOver().