HeatMapManager.cpp File Reference
#include <irrlicht.h>
*
#include `HeatMapManager.h`
*
#include <iostream>
*
#include `Game.h`
*
#include `SoundManager.h`
*
Variables
Game * hGame = hGame->GetInstance()
ISceneManager * hsmgr = hGame->device->getSceneManager()
IGUIEnvironment * ui = hGame->device->getGUIEnvironment()
SoundManager * hSoundManager
Variable Documentation
Game* hGame = hGame->GetInstance()
Referenced by HeatMapManager::CreateDangerZone(), HeatMapManager::CreatePoisonCloud(), and HeatMapManager::Update().
ISceneManager* hsmgr = hGame->device->getSceneManager()
Referenced by HeatMapManager::CreateDangerZone(), HeatMapManager::CreatePoisonCloud(), and HeatMapManager::Update().
SoundManager* hSoundManager
Referenced by HeatMapManager::CreatePoisonCloud(), and HeatMapManager::HeatMapManager().
IGUIEnvironment* ui = hGame->device->getGUIEnvironment()
Referenced by HeatMapManager::CreateCountdown().