InputReceiver Class Reference
#include <InputReceiver.h>
Public Member Functions
bool OnEvent (const irr::SEvent &event)
bool GetIsKeyDown (irr::EKEY_CODE keyCode)
irr::core::vector3df GetMousePosition ()
bool GetIsLeftMouseButtonPressed ()
InputReceiver ()
Private Attributes
bool isKeyDown [irr::KEY_KEY_CODES_COUNT]
irr::core::vector3df mousePosition
bool isLeftMouseButtonPressed
Constructor & Destructor Documentation
InputReceiver::InputReceiver ()
{
    // Set all states of the keys to be "not pressed"
    for (u32 i = 0; i < KEY_KEY_CODES_COUNT; ++i)
    {
        isKeyDown[i] = false;
    }
}
Member Function Documentation
bool InputReceiver::GetIsKeyDown (irr::EKEY_CODE keyCode)
Referenced by Player::Move().
{
    return isKeyDown[keyCode];
}
bool InputReceiver::GetIsLeftMouseButtonPressed ()
Referenced by Player::Shoot().
{
    return isLeftMouseButtonPressed;
}
vector3df InputReceiver::GetMousePosition ()
References mousePosition.
Referenced by Player::Shoot().
{
    return mousePosition;
}
bool InputReceiver::OnEvent (const irr::SEvent & event)
References mousePosition.
{
    if (event.EventType == EET_MOUSE_INPUT_EVENT)
    {
        switch (event.MouseInput.Event)
        {
        case EMIE_LMOUSE_PRESSED_DOWN:
            isLeftMouseButtonPressed = true;
            break;
        case EMIE_LMOUSE_LEFT_UP:
            isLeftMouseButtonPressed = false;
            break;
        case EMIE_MOUSE_MOVED:
            mousePosition.X = event.MouseInput.X;
            // Stores the event its y mouse position to z position
            mousePosition.Z = event.MouseInput.Y;
            break;
        default:
            break;
        }
    }
    // Remember whether each key is down or up
    if (event.EventType == irr::EET_KEY_INPUT_EVENT)
    {
        isKeyDown[event.KeyInput.Key] = event.KeyInput.PressedDown;
    }
    return false;
}
Member Data Documentation
bool InputReceiver::isKeyDown[irr::KEY_KEY_CODES_COUNT] [private]
bool InputReceiver::isLeftMouseButtonPressed [private]
irr::core::vector3df InputReceiver::mousePosition [private]
The documentation for this class was generated from the following files:
InputReceiver.h
InputReceiver.cpp