PowerupPool Class Reference
#include <PowerupPool.h>
Public Member Functions
PowerupPool (const PowerupPool &)=delete
PowerupPool & operator= (const PowerupPool &)=delete
Powerup * GetResource ()
void ReturnResource (Powerup *object)
Static Public Member Functions
static PowerupPool * GetInstance (irr::IrrlichtDevice *device)
Private Member Functions
PowerupPool (irr::IrrlichtDevice *device)
Private Attributes
std::list< Powerup * > resources
Static Private Attributes
static PowerupPool * instance = 0
Constructor & Destructor Documentation
PowerupPool::PowerupPool (const PowerupPool &) [delete]
Referenced by GetInstance().
PowerupPool::PowerupPool (irr::IrrlichtDevice * device) [private]
References powPoolDevice.
{ powPoolDevice = device; }
Member Function Documentation
PowerupPool * PowerupPool::GetInstance (irr::IrrlichtDevice * device) [static]
References instance, and PowerupPool().
Referenced by Player::Init(), and PowerUpSpawner::PowerUpDevice().
{
    if (!instance)
    {
        instance = new PowerupPool(device);
    }
    return instance;
}
Powerup * PowerupPool::GetResource ()
References powerup, powPoolDevice, and resources.
Referenced by PowerUpSpawner::PowerUpSpawn().
{
    if (resources.empty())
    {
        return new Powerup(powPoolDevice);
    }
    else
    {
        Powerup* powerup = resources.front();
        resources.pop_front();
        return powerup;
    }
}
PowerupPool& PowerupPool::operator= (const PowerupPool &) [delete]
void PowerupPool::ReturnResource (Powerup * object)
References resources.
Referenced by Player::Move().
{
    object->Reset();
    resources.push_back(object);
}
Member Data Documentation
PowerupPool * PowerupPool::instance = 0 [static], [private]
Referenced by GetInstance().
std::list<Powerup*> PowerupPool::resources [private]
Referenced by GetResource(), and ReturnResource().
The documentation for this class was generated from the following files:
PowerupPool.h
PowerupPool.cpp