GameOverState Class Reference
#include <GameOverState.h>
Public Member Functions
void ShowGameOver (irr::IrrlichtDevice *device)
Member Function Documentation
void GameOverState::ShowGameOver (irr::IrrlichtDevice * device)
References driver, gameOver, objPosition(), objRotate(), objScale(), and smgr.
Referenced by Player::TakeDamage().
{
    ISceneManager* smgr = device->getSceneManager();
    IVideoDriver* driver = device->getVideoDriver();
    IMesh* gameover = smgr->getMesh(gameOver);
    IMeshSceneNode* gameOverNode = smgr->addMeshSceneNode(gameover);
    if (gameOverNode) {
        gameOverNode->setScale(objScale);
        gameOverNode->setPosition(objPosition);
        gameOverNode->setMaterialTexture(0, driver->getTexture("../media/Textures/Game_Over_Screen.jpg"));
        gameOverNode->setRotation(objRotate);
        gameOverNode->setMaterialFlag(video::EMF_LIGHTING, false);
    }
}
The documentation for this class was generated from the following files:
GameOverState.h
GameOverState.cpp