EnemySpawner Class Reference
#include <EnemySpawner.h>
Public Member Functions
EnemySpawner (irr::IrrlichtDevice *device, Player *player)
void UpdateEnemies ()
irr::core::array< Enemy * > getActiveEnemies ()
Enemy * GetEnemy (int id)
void SpawnMathroskaMinion (irr::core::vector3df spawnPos, Enemy::EnemyType enemyType, irr::s32 nestAmount=0)
Static Public Member Functions
static EnemySpawner * GetSpawner ()
Private Member Functions
void NextWave ()
void Spawn ()
void InitialiseWaveData ()
Constructor & Destructor Documentation
EnemySpawner::EnemySpawner (irr::IrrlichtDevice * device, Player * player)
References _cam, _player, amountOfEnemies, enemSpawnSoundManager, enemyPool, enemySpawnerIDevice, enemySpawnerSmgr, game_EnemySpawner, EnemyPool::GetInstance(), Game::GetInstance(), SoundManager::GetInstance(), HeatMapManager::GetInstance(), Camera::GetInstance(), heatMapMngr, particleSystem, prevFrameTime, resize, spawner, and spawnPositions.
{
    particleSystem = new ParticleSystem(device);
    enemySpawnerIDevice = device;
    enemySpawnerSmgr = enemySpawnerIDevice->getSceneManager();
    _player = Player;
    game_EnemySpawner = game_EnemySpawner->
      GetInstance();
    heatMapMngr = heatMapMngr->GetInstance();
    enemyPool = EnemyPool::GetInstance(device);
    _cam = _cam->GetInstance(NULL);
    amountOfEnemies = 12;
    resize = 2;
    enemSpawnSoundManager = enemSpawnSoundManager->
      GetInstance();
    //setting spawnpositions in the corners.
    spawnPositions.push_back(vector3df(-82, 0, -78) * resize);
    spawnPositions.push_back(vector3df(78, 0, -78) * resize);
    spawnPositions.push_back(vector3df(78, 0, 78) * resize);
    spawnPositions.push_back(vector3df(-82, 0, 78) * resize);
    // In order to do framerate independent movement, we have to know
    // how long it was since the last frame
    prevFrameTime = enemySpawnerIDevice->getTimer()->getTime();
    InitialiseWaveData();
    spawner = this;
    Spawn();
}
Member Function Documentation
core::array< Enemy * > EnemySpawner::getActiveEnemies ()
References activeEnemies.
Referenced by Player::Shoot().
{ return activeEnemies; }
Enemy * EnemySpawner::GetEnemy (int id)
References activeEnemies.
Referenced by Player::Shoot().
{ return activeEnemies[id]; }
EnemySpawner * EnemySpawner::GetSpawner () [static]
References spawner.
Referenced by Enemy::TakeDamage().
{ return spawner; }
void EnemySpawner::InitialiseWaveData () [private]
References waveData.
{
    //Amount of enemies:
    waveData[0] = new WaveData(0, 0, 0, 0, 0);//5
    waveData[1] = new WaveData(1, 5, 0, 0, 0);//5
    waveData[2] = new WaveData(2, 10, 0, 0, 0);//10
    waveData[3] = new WaveData(3, 8, 3, 0, 0);//11
    waveData[4] = new WaveData(4, 12, 5, 0, 0);//17
    waveData[5] = new WaveData(5, 15, 2, 2, 2);//20
    waveData[6] = new WaveData(6, 10, 0, 7, 2);//18
    waveData[7] = new WaveData(7, 7, 7, 4, 2); //20
    waveData[8] = new WaveData(8, 0, 15, 0, 5); //20
    waveData[9] = new WaveData(9, 0, 0, 15, 7); //22
    waveData[10] = new WaveData(10, 10, 10, 10, 8); //38
    waveData[11] = new WaveData(11, 0, 15, 15, 10); //40
    waveData[12] = new WaveData(12, 10, 10, 10, 10); //40
    waveData[13] = new WaveData(13, 15, 15, 15, 15); //40
    waveData[14] = new WaveData(14, 20, 20, 20, 20); //40
}
void EnemySpawner::NextWave () [private]
References _cam, BIG_WAVE_INCOMING_SOUND, Camera::bigWaveShaking, currentTime, currentWave, enemSpawnSoundManager, enemySpawnerIDevice, maxWaveCooldown, newWave, SoundManager::PlaySound(), Camera::state, WAVE_INCOMING_SOUND, waveChangeUI, waveCooldown, Camera::waveShaking, and waveTimerSet.
{
    const u32 now_ = enemySpawnerIDevice->getTimer()->getTime();
    const f32 frameTime = (f32)(now_ - currentTime) / 1000.f; // Time in seconds
    currentTime = now_;
    if (waveTimerSet == false && waveCooldown > 0)
    {
        if (newWave)
        {
            if ((currentWave + 1) % 5 == 0)
                enemSpawnSoundManager->PlaySound(
      BIG_WAVE_INCOMING_SOUND, false);
            else
                enemSpawnSoundManager->PlaySound(
      WAVE_INCOMING_SOUND, false);
            newWave = false;
        }
        waveChangeUI = true;
        waveCooldown -= frameTime;
        if (waveCooldown <= 0)
        {
            currentWave++;
            Spawn();
            if (currentWave % 5 == 0)
            {
                _cam->state = _cam->bigWaveShaking;
                newWave = true;
            }
            else
            {
                _cam->state = _cam->waveShaking;
                newWave = true;
            }
            //Insert pause/UI between waves here
            waveTimerSet = true;
            waveCooldown = maxWaveCooldown;
            waveChangeUI = false;
            waveTimerSet = false;
        }
    }
}
void EnemySpawner::Spawn () [private]
References _player, activeEnemies, Collision::AddDynamicToList(), collision, currentWave, enemy, enemyPool, Enemy::GetEnemySceneNode(), EnemyPool::GetResource(), WaveData::maxFastEnem, WaveData::maxMatroEnem, WaveData::maxRegularEnem, WaveData::maxTankEnem, Enemy::SetEnemyType(), Enemy::SetPlayer(), spawnPositions, time, and waveData.
{
    for (int i = 0; i < waveData[currentWave]->maxRegularEnem; i++)
    {
        srand(time(NULL) * i);
        u32 randomPos = rand() % 4;
        enemy = enemyPool->GetResource();
        enemy->SetPlayer(_player);
        enemy->SetEnemyType(Enemy::EnemyType::basic);
        enemy->GetEnemySceneNode()->setPosition(
      spawnPositions[randomPos]);
        collision.AddDynamicToList(enemy->
      GetEnemySceneNode());
        activeEnemies.push_back(enemy);
    }
    for (int j = 0; j < waveData[currentWave]->maxFastEnem; j++)
    {
        srand(time(NULL) * j);
        u32 randomPos = rand() % 4;
        enemy = enemyPool->GetResource();
        enemy->SetPlayer(_player);
        enemy->SetEnemyType(Enemy::EnemyType::fast);
        enemy->GetEnemySceneNode()->setPosition(
      spawnPositions[randomPos]);
        collision.AddDynamicToList(enemy->
      GetEnemySceneNode());
        activeEnemies.push_back(enemy);
    }
    for (int k = 0; k < waveData[currentWave]->maxTankEnem; k++)
    {
        srand(time(NULL) * k);
        u32 randomPos = rand() % 4;
        enemy = enemyPool->GetResource();
        enemy->SetPlayer(_player);
        enemy->SetEnemyType(Enemy::EnemyType::tanky);
        enemy->GetEnemySceneNode()->setPosition(
      spawnPositions[randomPos]);
        collision.AddDynamicToList(enemy->
      GetEnemySceneNode());
        activeEnemies.push_back(enemy);
    }
    for (int k = 0; k < waveData[currentWave]->maxMatroEnem; k++)
    {
        srand(time(NULL) * k);
        u32 randomPos = rand() % 4;
        enemy = enemyPool->GetResource();
        enemy->SetPlayer(_player);
        enemy->SetEnemyType(Enemy::EnemyType::matroshka, 2);
        enemy->GetEnemySceneNode()->setPosition(
      spawnPositions[randomPos]);
        collision.AddDynamicToList(enemy->
      GetEnemySceneNode());
        activeEnemies.push_back(enemy);
    }
}
void EnemySpawner::SpawnMathroskaMinion (irr::core::vector3df spawnPos, Enemy::EnemyType enemyType, irr::s32 nestAmount = 0)
References _player, activeEnemies, Collision::AddDynamicToList(), collision, enemy, enemyPool, Enemy::GetEnemySceneNode(), EnemyPool::GetResource(), Enemy::SetEnemyType(), and Enemy::SetPlayer().
Referenced by Enemy::TakeDamage().
{
    enemy = enemyPool->GetResource();
    enemy->SetPlayer(_player);
    enemy->SetEnemyType(enemyType, nestAmount);
    enemy->GetEnemySceneNode()->setPosition(spawnPos);
    collision.AddDynamicToList(enemy->
      GetEnemySceneNode());
    activeEnemies.push_back(enemy);
}
void EnemySpawner::UpdateEnemies ()
References activeEnemies, HeatMapManager::AddWeight(), bloodSplatter, HeatMapManager::CheckZoneFromPosition(), collision, ParticleSystem::CreateParticles(), currentWave, enemyPool, enemySpawnerIDevice, enemySpawnerSmgr, frameDeltaTime, game_EnemySpawner, Game::GetIsGameOver(), heatMapMngr, maxWaves, particleSystem, powerUpPositionAdjust, PowerUpSpawner::PowerUpSpawn(), powerUpSpawner, prevFrameTime, Collision::RemoveDynamicFromList(), EnemyPool::ReturnResource(), ParticleSystem::Update(), and waveTimerSet.
Referenced by Game::Update().
{
    // Work out a frame delta time.
    const u32 now = enemySpawnerIDevice->getTimer()->getTime();
    //enemySpawnerIDevice->getTimer()->start();
    const f32 frameDeltaTime = (f32)(now - prevFrameTime) / 1000.f; // Time in
       seconds
    prevFrameTime = now;
    particleSystem->Update(frameDeltaTime);
    // Update all enemies
    for (int i = 0; i < activeEnemies.size(); i++)
    {
        activeEnemies[i]->Update(frameDeltaTime);
        if (activeEnemies[i]->IsDead())
        {
            particleSystem->CreateParticles(
      activeEnemies[i]->GetEnemySceneNode()->getPosition(), bloodSplatter);// for
       creating blood on enemies
            heatMapMngr->AddWeight(heatMapMngr->
      CheckZoneFromPosition(activeEnemies[i]->GetEnemySceneNode()->
      getAbsolutePosition()), 5.0f);
            powerUpSpawner->PowerUpSpawn(activeEnemies[i]->
      GetEnemySceneNode()->getPosition() - powerUpPositionAdjust); //to lower the powerup position
            enemyPool->ReturnResource(activeEnemies[i]);
            collision.RemoveDynamicFromList(
      activeEnemies[i]->GetEnemySceneNode());
            activeEnemies.erase(i);
        }
        if (game_EnemySpawner->GetIsGameOver())
        {
            enemySpawnerSmgr->addToDeletionQueue(activeEnemies[i]->
      GetEnemySceneNode());
            activeEnemies.erase(i);
        }
    }
    if (activeEnemies.size() <= 0 && currentWave <
      maxWaves)
    {
        if (waveTimerSet == false)
        {
            NextWave();
        }
    }
}
The documentation for this class was generated from the following files:
EnemySpawner.h
EnemySpawner.cpp