Enemy Class Reference
#include <Enemy.h>
Public Types
enum EnemyType { basic,
fast,
tanky,
matroshka
 }
Public Member Functions
void Reset ()
irr::scene::ISceneNode * GetEnemySceneNode ()
bool IsDead ()
void SetEnemyType (EnemyType type, int nestAmount=0)
void SetEnemy (irr::scene::ISceneNode *newEnemy)
void SetPlayer (Player *_player)
void Update (float frameDeltaTime)
void Attack ()
void TakeDamage (irr::f32 damage)
Enemy (irr::IrrlichtDevice *device)
Private Attributes
irr::scene::ISceneNode * enemy
irr::core::vector3df velocity
irr::core::vector3df delta
EnemyType enemyType
bool dead
float health
float speed
float damage
int nestingLvl
Member Enumeration Documentation
enum Enemy::EnemyType
Enumerator
basic
fast
tanky
matroshka
                   {
        basic,
        fast,
        tanky,
        matroshka
    };
Constructor & Destructor Documentation
Enemy::Enemy (irr::IrrlichtDevice * device)
References enemy, enemyDriver, enemyIDevice, enemySmgr, enemySoundManager, SoundManager::GetInstance(), and scaleVect.
{
    enemyIDevice = device;
    enemyDriver = enemyIDevice->getVideoDriver();
    enemySmgr = enemyIDevice->getSceneManager();
    enemySoundManager = enemySoundManager->
      GetInstance();
    dead = false;
    enemy = 0;
    enemy = enemySmgr->addMeshSceneNode(enemySmgr->getMesh("
      ../media/Models/enemy/zombie.3ds"));
    if (enemy)
    {
        enemy->setMaterialFlag(video::EMF_LIGHTING, false);
        enemy->setScale(scaleVect);
        enemy->setRotation(vector3df(0, -90, 0));
        enemy->setMaterialTexture(0, enemyDriver->getTexture("
      ../media/Textures/zombieskin.png"));
    }
    SetEnemyType(EnemyType::basic);
}
Member Function Documentation
void Enemy::Attack ()
References Player::getVulnerableTimer(), player, and Player::TakeDamage().
{
    if (!(player->getVulnerableTimer() > 0))
    {
        player->TakeDamage(damage);
    }
}
ISceneNode * Enemy::GetEnemySceneNode ()
References enemy.
Referenced by EnemyPool::GetResource(), EnemySpawner::Spawn(), and EnemySpawner::SpawnMathroskaMinion().
{ return enemy; }
bool Enemy::IsDead ()
{ return dead; }
void Enemy::Reset ()
References enemy.
{
    SetEnemyType(EnemyType::basic);
    dead = false;
    enemy->setVisible(false);
    enemy->setPosition(vector3df(0, 0, 0));
}
void Enemy::SetEnemy (irr::scene::ISceneNode * newEnemy)
References enemy.
{ enemy = newEnemy; }
void Enemy::SetEnemyType (EnemyType type, int nestAmount = 0)
References enemy, enemyDriver, and health.
Referenced by EnemySpawner::Spawn(), and EnemySpawner::SpawnMathroskaMinion().
{
    enemyType = type;
    switch (type)
    {
    case EnemyType::basic:
        enemy->setScale(vector3df(2.0f, 2.0f, 2.0f));
        health = 120;
        speed = 30.f;
        damage = 20.f;
        enemy->setMaterialTexture(0, enemyDriver->getTexture("
      ../media/Textures/zombieskin.png"));
        return;
    case EnemyType::fast:
        enemy->setScale(vector3df(1.7f, 1.7f, 1.7f));
        health = 70;
        speed = 45.f;
        damage = 10.f;
        enemy->setMaterialTexture(0, enemyDriver->getTexture("
      ../media/Textures/fastskin.png"));
        return;
    case EnemyType::tanky:
        enemy->setScale(vector3df(3.0f, 3.0f, 3.0f));
        health = 200;
        speed = 15.f;
        damage = 30.f;
        enemy->setMaterialTexture(0, enemyDriver->getTexture("
      ../media/Textures/tankyskin.png"));
        return;
    case EnemyType::matroshka:
        nestingLvl = nestAmount;
        switch (nestAmount)
        {
        case 2:
            enemy->setScale(vector3df(2.5f, 2.5f, 2.5f));
            health = 160;
            speed = 15.f;
            damage = 20.f;
            enemy->setMaterialTexture(0, enemyDriver->getTexture("
      ../media/Textures/matroshkaskin.png"));
            break;
        case 1:
            enemy->setScale(vector3df(2.0f, 2.0f, 2.0f));
            health = 80;
            speed = 20.f;
            damage = 15.f;
            enemy->setMaterialTexture(0, enemyDriver->getTexture("
      ../media/Textures/tankyskin.png"));
            break;
        case 0:
            enemy->setScale(vector3df(1.5f, 1.5f, 1.5f));
            health = 40;
            speed = 25.f;
            damage = 10.f;
            enemy->setMaterialTexture(0, enemyDriver->getTexture("
      ../media/Textures/fastskin.png"));
            break;
        default:
            break;
        }
        return;
    }
}
void Enemy::SetPlayer (Player * _player)
References _player, and player.
Referenced by EnemySpawner::Spawn(), and EnemySpawner::SpawnMathroskaMinion().
{ player = _player; }
void Enemy::TakeDamage (irr::f32 damage)
References enemySoundManager, EnemySpawner::GetSpawner(), health, SoundManager::PlaySound(), EnemySpawner::SpawnMathroskaMinion(), ZOMBIE_DEATH_SOUND1, ZOMBIE_DEATH_SOUND2, and ZOMBIE_TAKE_DAMAGE_SOUND.
Referenced by Player::Shoot().
{
    if (health > 0) {
        enemySoundManager->PlaySound(
      ZOMBIE_TAKE_DAMAGE_SOUND, false);
        health -= damage;
    }
    else
    {
        health = 0;
        dead = true;
        switch (rand() % 2)
        {
        case 0:
            enemySoundManager->PlaySound(
      ZOMBIE_DEATH_SOUND1, false);
            break;
        case 1:
            enemySoundManager->PlaySound(
      ZOMBIE_DEATH_SOUND2, false);
            break;
        }
        if (enemyType == EnemyType::matroshka && nestingLvl > 0)
        {
            EnemySpawner* espawner = espawner->GetSpawner();
            for (int i = 0; i < 2; i++)
            {
                espawner->SpawnMathroskaMinion(
      GetEnemySceneNode()->getPosition(), EnemyType::matroshka,
      nestingLvl-1);
            }
        }
    }
}
void Enemy::Update (float frameDeltaTime)
References enemy, Player::getPlayerObject(), meleeRange, and player.
{
    // Get position delta compared to player position
    vector3df enemyPosition = enemy->getPosition();
    vector3df delta = player->getPlayerObject()->getPosition() - enemyPosition;
      // Save delta
    vector3df deltaNormalized = delta;
    deltaNormalized.normalize(); // It is done in two lines, so the delta doesnt get normalized
    enemy->setRotation(vector3df(0, atan2(deltaNormalized.X, deltaNormalized.Z) * 180 / PI, 0));
    // Change position based on delta and speed
    if (delta.getLength() > meleeRange) // If farther than melee attack range,
    {
        // Move towards player
        enemyPosition += deltaNormalized * frameDeltaTime * speed;
        vector3df oldPosition = enemy->getPosition();
        enemy->setPosition(enemyPosition);
    }
    else
        Attack();
}
Member Data Documentation
float Enemy::damage [private]
bool Enemy::dead [private]
irr::core::vector3df Enemy::delta [private]
irr::scene::ISceneNode* Enemy::enemy [private]
EnemyType Enemy::enemyType [private]
float Enemy::health [private]
int Enemy::nestingLvl [private]
float Enemy::speed [private]
irr::core::vector3df Enemy::velocity [private]
The documentation for this class was generated from the following files:
Enemy.h
Enemy.cpp