SoundManager Class Reference
#include <SoundManager.h>
Public Member Functions
SoundManager (const SoundManager &)=delete
SoundManager & operator= (const SoundManager &)=delete
void PlaySound (const char *sound, bool loop)
Static Public Member Functions
static SoundManager * GetInstance ()
Public Attributes
irrklang::ISoundEngine * engine
Private Member Functions
SoundManager ()
Static Private Attributes
static SoundManager * instance = 0
Constructor & Destructor Documentation
SoundManager::SoundManager (const SoundManager &) [delete]
SoundManager::SoundManager () [private]
{
    engine = createIrrKlangDevice();
}
Member Function Documentation
SoundManager * SoundManager::GetInstance () [static]
Referenced by Camera::Camera(), Enemy::Enemy(), EnemySpawner::EnemySpawner(), HeatMapManager::HeatMapManager(), Player::Player(), and Game::Start().
{
    if (!instance)
    {
        instance = new SoundManager();
    }
    return instance;
}
SoundManager& SoundManager::operator= (const SoundManager &) [delete]
void SoundManager::PlaySound (const char * sound, bool loop)
Referenced by Camera::CameraUpdate(), HeatMapManager::CreatePoisonCloud(), Player::Move(), EnemySpawner::NextWave(), Player::Shoot(), Game::Start(), Enemy::TakeDamage(), and Player::TakeDamage().
{
    engine->play2D(sound, loop);
}
Member Data Documentation
irrklang::ISoundEngine* SoundManager::engine
SoundManager * SoundManager::instance = 0 [static], [private]
The documentation for this class was generated from the following files:
SoundManager.h
SoundManager.cpp