Tutorial Class Reference
Tutorial class which displays the buttons to use and the objective of the game.
#include <Tutorial.h>
Public Member Functions
void ShowTutorial (irr::IrrlichtDevice *device)
Shows the tutorial GUI.
void RemoveTutorial ()
Removes the tutorial GUI.
void Update (irr::f32 frameDeltaTime)
Update for tutorial GUI.
Public Attributes
bool isTutorialActive = true
Detailed Description
Tutorial class which displays the buttons to use and the objective of the game.
Member Function Documentation
void Tutorial::RemoveTutorial ()
Removes the tutorial GUI.
References img.
Referenced by Game::SetIsGameOver().
{
    if(img)
    {
        img->remove();
        img = NULL;
    }
}
void Tutorial::ShowTutorial (irr::IrrlichtDevice * device)
Shows the tutorial GUI.
References driver, img, smgr, and tutorialGUI.
Referenced by Game::Start().
{
    ISceneManager* smgr = device->getSceneManager();
    IVideoDriver* driver = device->getVideoDriver();
    tutorialGUI = device->getGUIEnvironment();
    ITexture* tutorialImage = driver->getTexture("../media/Textures/Tutorial_Resize.png");
    img = tutorialGUI->addImage(tutorialImage, position2d<int>(250, 90));
}
void Tutorial::Update (irr::f32 frameDeltaTime)
Update for tutorial GUI.
References frameDeltaTime, img, and timer.
Referenced by Game::Update().
{
    if (img)
    {
        if (timer > 0)
        {
            timer -= frameDeltaTime;
        }
        else
        {
            isTutorialActive = false;
            RemoveTutorial();
        }
    }
}
Member Data Documentation
bool Tutorial::isTutorialActive = true
Referenced by Game::Update().
The documentation for this class was generated from the following files:
Tutorial.h
Tutorial.cpp