Powerup Class Reference
#include <Powerup.h>
Public Types
enum PowerupType { health,
firerate,
splitshot,
base
 }
Public Member Functions
void Reset ()
irr::scene::ISceneNode * GetNode ()
void SetPowerup (irr::scene::ISceneNode *newPowerup)
irr::s32 GetPowerupType ()
Powerup (irr::IrrlichtDevice *device)
void SetPowerupType (irr::s32 powType)
Private Attributes
irr::scene::ISceneNode * powerup
PowerupType type
Member Enumeration Documentation
enum Powerup::PowerupType
Enumerator
health
firerate
splitshot
base
    {
        health, firerate, splitshot, base
    };
Constructor & Destructor Documentation
Powerup::Powerup (irr::IrrlichtDevice * device)
References powerup, powerupDriver, powerupIDevice, and powerupSmgr.
{
    powerupIDevice = device;
    powerupDriver = powerupIDevice->getVideoDriver();
    powerupSmgr = powerupIDevice->getSceneManager();
    powerup = 0;
    SetPowerupType(PowerupType::base);
}
Member Function Documentation
ISceneNode * Powerup::GetNode ()
References powerup.
{
    return powerup;
}
s32 Powerup::GetPowerupType ()
Referenced by Player::Move().
{
    return type;
}
void Powerup::Reset ()
References powerup.
{
    powerup->setVisible(false);
    powerup->setPosition(vector3df(0, 0, 0));
}
void Powerup::SetPowerup (irr::scene::ISceneNode * newPowerup)
References powerup.
Referenced by PowerUpSpawner::PowerUpSpawn().
{
    powerup = newPowerup;
}
void Powerup::SetPowerupType (irr::s32 powType)
References health, powerup, powerupDriver, and type.
Referenced by PowerUpSpawner::PowerUpSpawn().
{
    switch (powType)
    {
    case 0:
        Powerup::type = Powerup::PowerupType::health;
        powerup->setMaterialTexture(0, powerupDriver->getTexture("
      ../media/Textures/Health_Cross.png"));
        break;
    case 1:
        Powerup::type = Powerup::PowerupType::firerate;
        powerup->setMaterialTexture(0, powerupDriver->getTexture("
      ../media/Textures/rapidfire_texture.png"));
        break;
    case 2:
        Powerup::type = Powerup::PowerupType::splitshot;
        powerup->setMaterialTexture(0, powerupDriver->getTexture("
      ../media/Textures/splitshot_texture.png"));
        break;
    default:
        Powerup::type = Powerup::PowerupType::base;
        break;
    }
}
Member Data Documentation
irr::scene::ISceneNode* Powerup::powerup [private]
PowerupType Powerup::type [private]
Referenced by SetPowerupType().
The documentation for this class was generated from the following files:
Powerup.h
Powerup.cpp