Player Class Reference
A player.
#include <Player.h>
Public Member Functions
Player (irr::IrrlichtDevice *device)
Constructor.
void TakeDamage (irr::f32 damage)
Take damage.
void DrawHealthBar ()
Draw health bar.
void Move (InputReceiver inputReceiver)
Moves the given input receiver.
void Shoot (InputReceiver inputReceiver, EnemySpawner *enemies)
Shoots.
irr::scene::ISceneNode * getPlayerObject ()
Gets player object.
irr::scene::ISceneNode * getCamFollowObject ()
void Raycast (irr::core::vector3df endPosition, irr::scene::ICameraSceneNode *camera)
Raycasts.
bool OnLineIntersect (irr::core::plane3df &plane, irr::core::line3df &ray)
Executes the line intersect action.
irr::s32 getVulnerableTimer ()
Gets vulnerable timer.
irr::core::vector3df GetMousePosition ()
Gets mouse position.
s32 GetRapidFireTimer ()
s32 GetSplitFireTimer ()
Private Member Functions
void Init ()
Initializes this object.
Private Attributes
irr::s32 bulletTimer
The bullet timer.
irr::s32 rapidFireTimer
The rapid fire power up timer.
irr::s32 splitFireTimer
The split fire power up timer.
Detailed Description
A player.
Constructor & Destructor Documentation
Player::Player (irr::IrrlichtDevice * device)
Constructor.
References game, Game::GetInstance(), SoundManager::GetInstance(), playerDriver, playerIDevice, playerSmgr, soundManager, and time.
{
    soundManager = soundManager->GetInstance();
    playerIDevice = device;
    playerDriver = playerIDevice->getVideoDriver();
    playerSmgr = playerIDevice->getSceneManager();
    game = game->GetInstance();
    Init();
    // In order to do framerate independent movement, we have to know
    // how long it was since the last frame
    time = playerIDevice->getTimer()->getTime();
}
Member Function Documentation
void Player::DrawHealthBar ()
Draw health bar.
References game, Game::GetIsGameOver(), health, MAX_HEALTH, playerDriver, X1BAR, X2BAR, Y1BAR, and Y2BAR.
Referenced by Game::Draw().
{
    if (game->GetIsGameOver() != true)
    {
        const s32 barSize = MAX_HEALTH;
        //draws multiple bars to make i look nice
        playerDriver->draw2DRectangle(SColor(255, 100, 100, 100), rect<s32>(
      X1BAR, Y1BAR, (barSize * 5) + X2BAR, Y2BAR));
        playerDriver->draw2DRectangle(SColor(255, 125, 125, 125), rect<s32>(
      X1BAR + 1, Y1BAR + 1, barSize * 5 + X2BAR - 1, Y2BAR - 1));
        playerDriver->draw2DRectangle(SColor(255, 150, 150, 150), rect<s32>(
      X1BAR + 3, Y1BAR + 3, barSize * 5 + X2BAR - 3, Y2BAR - 3));
        playerDriver->draw2DRectangle(rect<s32>(X1BAR + 3,
      Y1BAR + 3, health * 5 + X2BAR - 3, Y2BAR - 3),
            SColor(255, 255 - health * 2.55, health*2.55, 0),
            SColor(255, 255 - health * 2.55, health*2.55, 0),
            SColor(255, 255 - health * 2.55, health*2.55 - 150, 0),
            SColor(255, 255 - health * 2.55, health*2.55 - 150, 0));
    }
}
irr::scene::ISceneNode * Player::getCamFollowObject ()
References camFollowObject.
Referenced by Camera::ScreenShake().
{
    return camFollowObject;
}
vector3df Player::GetMousePosition ()
Gets mouse position.
References mousePosition.
{
    return mousePosition;
}
ISceneNode * Player::getPlayerObject ()
Gets player object.
References playerObject.
Referenced by Camera::CameraUpdate(), Camera::ScreenShake(), and Enemy::Update().
{
    return playerObject;
}
s32 Player::GetRapidFireTimer ()
Referenced by UISystem::WaveUI().
{
    return rapidFireTimer;
}
s32 Player::GetSplitFireTimer ()
Referenced by UISystem::WaveUI().
{
    return splitFireTimer;
}
s32 Player::getVulnerableTimer ()
Gets vulnerable timer.
References vulnerableTimer.
Referenced by Enemy::Attack().
{
    return vulnerableTimer;
}
void Player::Init () [private]
Initializes this object.
References _Cam, Collision::AddDynamicToList(), BULLET_BASE_TIMER, camFollowObject, currentPosition, PowerupPool::GetInstance(), Camera::GetInstance(), BulletPool::GetInstance(), GUN_COLOR, GUN_MODEL, gunNode, health, MAX_HEALTH, PLAYER_MODEL, playerCol, playerDriver, playerIDevice, playerObject, playerSmgr, pool, and powPool.
{
    health = MAX_HEALTH;
    IMesh* playerMesh = playerSmgr->getMesh(PLAYER_MODEL);
    playerObject = playerSmgr->addMeshSceneNode(playerMesh, 0, -1, vector3df(266, 0,
      266), vector3df(0, 0, 0));
    camFollowObject = playerSmgr->addCubeSceneNode();
    if (playerObject)
    {
        playerObject->setMaterialFlag(EMF_LIGHTING, true);
    }
    if (camFollowObject)
    {
        camFollowObject->setParent(playerObject);
        camFollowObject->setScale(vector3df(0,0,0));
    }
    currentPosition = playerObject->getPosition();
    playerCol.AddDynamicToList(playerObject);
    IMesh* gunModel = playerSmgr->getMesh(GUN_MODEL);
    gunNode = playerSmgr->addMeshSceneNode(gunModel);
    if (gunNode)
    {
        gunNode->setPosition(vector3df(2, 5, -1));
        gunNode->setScale(vector3df(0.125f, 0.125f, 0.125f));
        gunNode->setMaterialFlag(EMF_LIGHTING, true);
        gunNode->setMaterialTexture(0, playerDriver->getTexture(
      GUN_COLOR));
        playerObject->addChild(gunNode);
    }
    // Get the instance of BulletPool
    pool = pool->GetInstance();
    powPool = powPool->GetInstance(playerIDevice);
    _Cam = _Cam->GetInstance(NULL);
    // Set the timer to the bullet base time
    bulletTimer = BULLET_BASE_TIMER;
}
void Player::Move (InputReceiver inputReceiver)
Moves the given input receiver.
References HeatMapManager::activeZone, HeatMapManager::AddWeight(), HeatMapManager::CheckZoneFromPosition(), Collision::CollidesWithPowerup(), Collision::CollidesWithStaticObjects(), currentPosition, frameDeltaTime, InputReceiver::GetIsKeyDown(), Powerup::GetPowerupType(), health, HEALTH_SOUND, heatMapManager, HeatMapManager::isPoisonCloudActive, mousePosition, MOVEMENT_SPEED, playerCol, playerIDevice, playerObject, SoundManager::PlaySound(), powPool, RAPID_FIRE_SOUND, RAPID_SPLIT_FIRE_SOUND, PowerupPool::ReturnResource(), soundManager, SPLIT_FIRE_SOUND, time, HeatMapManager::Update(), vulnerableTimer, and Y_AXIS_CORRECTION.
Referenced by Game::Update().
{
    // Work out a frame delta time.
    u32 now = playerIDevice->getTimer()->getTime();
    frameDeltaTime = (f32)(now - time) / 1000.f;
    time = now;
    vector3df newPosition = playerObject->getPosition();
    if (playerCol.CollidesWithStaticObjects(
      playerObject))
        currentPosition = playerObject->getPosition();
    if (inputReceiver.GetIsKeyDown(irr::KEY_KEY_W))
    {
        newPosition.X += frameDeltaTime * MOVEMENT_SPEED;
    }
    else if (inputReceiver.GetIsKeyDown(irr::KEY_KEY_S))
    {
        newPosition.X -= frameDeltaTime * MOVEMENT_SPEED;
    }
    if (inputReceiver.GetIsKeyDown(irr::KEY_KEY_A))
    {
        newPosition.Z += frameDeltaTime * MOVEMENT_SPEED;
    }
    else if (inputReceiver.GetIsKeyDown(irr::KEY_KEY_D))
    {
        newPosition.Z -= frameDeltaTime * MOVEMENT_SPEED;
    }
    playerObject->setPosition(newPosition);
    heatMapManager->AddWeight(heatMapManager->
      CheckZoneFromPosition(newPosition), frameDeltaTime*2);
    if (heatMapManager->CheckZoneFromPosition(newPosition) ==
      heatMapManager->activeZone && heatMapManager->
      isPoisonCloudActive) {
        TakeDamage(1);
    }
    heatMapManager->Update();
    // Calculate the angle using atan2 using the mouse position and the player object
    float angle = atan2(mousePosition.Z - playerObject->getPosition().Z,
        mousePosition.X - playerObject->getPosition().X);
    // Calculate the inverted angle
    angle *= -(RADTODEG);
    // Set the angle value to be between 0 and 360
    if (angle < 0)
    {
        angle = 360 - (-angle);
    }
    // Rotate player towards mouse position using the Y Axis correction and the calculated angle
    playerObject->setRotation(vector3df(0, Y_AXIS_CORRECTION + angle, 0));
    if (vulnerableTimer > 0)
    {
        vulnerableTimer -= frameDeltaTime;
    }
    Powerup* pow = playerCol.CollidesWithPowerup(
      playerObject);
    if (pow)
    {
        switch (pow->GetPowerupType())
        {
        case 0:
            health += 25;
            soundManager->PlaySound(HEALTH_SOUND, false);
            if (health > 100)
                health = 100;
            break;
        case 1:
            rapidFireTimer = 1000;
            if (splitFireTimer > 0)
                soundManager->PlaySound(
      RAPID_SPLIT_FIRE_SOUND, false);
            else
                soundManager->PlaySound(RAPID_FIRE_SOUND, false);
            break;
        case 2:
            splitFireTimer = 1000;
            if (rapidFireTimer > 0)
                soundManager->PlaySound(
      RAPID_SPLIT_FIRE_SOUND, false);
            else
                soundManager->PlaySound(SPLIT_FIRE_SOUND, false);
            
            break;
        }
        powPool->ReturnResource(pow);
        
    }
}
bool Player::OnLineIntersect (irr::core::plane3df & plane, irr::core::line3df & ray)
Executes the line intersect action.
References mousePosition.
{
    return plane.getIntersectionWithLine(ray.start, ray.getVector(),
      mousePosition);
}
void Player::Raycast (irr::core::vector3df endPosition, irr::scene::ICameraSceneNode * camera)
Raycasts.
References gunNode, mousePosition, playerObject, playerSmgr, and toMousePos.
{
    vector3df planeNormal = vector3df(0, -1, 0);
    vector2di rayScreenCoordination = vector2di(endPosition.X, endPosition.Z);
    // Create a ray through the screen coordinates.
    line3df ray = playerSmgr->getSceneCollisionManager()->getRayFromScreenCoordinates(
      rayScreenCoordination, camera);
    plane3df plane(playerObject->getPosition(), planeNormal);
    if (OnLineIntersect(plane, ray))
    {
        toMousePos = vector3df(mousePosition - gunNode->getPosition());
    }
}
void Player::Shoot (InputReceiver inputReceiver, EnemySpawner * enemies)
Shoots.
References _Cam, activeBullets, bulletSize, Collision::CollidesWithStaticObjects(), Score::DisplayScore(), frameDeltaTime, EnemySpawner::getActiveEnemies(), Bullet::GetBullet(), Bullet::GetBulletTimer(), EnemySpawner::GetEnemy(), InputReceiver::GetIsLeftMouseButtonPressed(), InputReceiver::GetMousePosition(), BulletPool::GetResource(), GUN_SHOT_SOUND, hasShot, mousePosition, playerCol, playerObject, playerScores, playerSmgr, SoundManager::PlaySound(), pool, RAPID_FIRING_SOUND, RAPID_SPLIT_FIRING_SOUND, BulletPool::ReturnResource(), Collision::SceneNodeWithSceneNode(), Bullet::SetBullet(), Bullet::SetBulletMode(), Bullet::SetBulletSpread(), Camera::shootShaking, soundManager, SPLIT_FIRING_SOUND, Camera::state, and Enemy::TakeDamage().
Referenced by Game::Update().
{
    Raycast(inputReceiver.GetMousePosition(), playerSmgr->getActiveCamera(
      ));
    if (bulletTimer > 0)
    {
        bulletTimer -= frameDeltaTime;
    }
    if (rapidFireTimer > 0)
    {
        rapidFireTimer -= frameDeltaTime;
    }
    if (splitFireTimer > 0)
    {
        splitFireTimer -= frameDeltaTime;
    }
    if (inputReceiver.GetIsLeftMouseButtonPressed() &&
      bulletTimer <= 0)
    {
        if (rapidFireTimer > 0 && splitFireTimer > 0)
            soundManager->PlaySound(
      RAPID_SPLIT_FIRING_SOUND, false);
        else
        {
            if (rapidFireTimer > 0)
                soundManager->PlaySound(RAPID_FIRING_SOUND, false);
            else if (splitFireTimer > 0)
                soundManager->PlaySound(SPLIT_FIRING_SOUND, false);
            else
                soundManager->PlaySound(GUN_SHOT_SOUND, false);
        }
            
        
        // Bullet instance
        Bullet* bullet = pool->GetResource();
        // Main bullet
        bullet->SetBullet(playerSmgr->addCubeSceneNode(10.f, 0, -1,
      playerObject->getPosition(), playerObject->getRotation(),
      bulletSize));
        if (bullet->GetBullet())
        {
            bullet->GetBullet()->setVisible(false);
        }
        // Rapid fire active
        if (rapidFireTimer > 0 && splitFireTimer <= 0)
        {
            bullet->SetBulletMode(Bullet::BulletMode::rapidFire);
        }
        // Split fire active
        if (splitFireTimer > 0 && rapidFireTimer <= 0)
        {
            // Bullet left/right instances
            Bullet* leftBullet = pool->GetResource();
            Bullet* rightBullet = pool->GetResource();
            leftBullet->SetBulletMode(Bullet::BulletMode::splitFire);
            rightBullet->SetBulletMode(Bullet::BulletMode::splitFire);
            leftBullet->SetBulletSpread(-0.1f);
            rightBullet->SetBulletSpread(0.1f);
            // Left bullet for split fire
            leftBullet->SetBullet(playerSmgr->addCubeSceneNode(10.f, 0, -1,
      playerObject->getPosition(), playerObject->getRotation(),
      bulletSize));
            if (leftBullet->GetBullet())
            {
                leftBullet->GetBullet()->setVisible(false);
            }
            // Right bullet for split fire
            rightBullet->SetBullet(playerSmgr->addCubeSceneNode(10.f, 0, -1,
      playerObject->getPosition(), playerObject->getRotation(),
      bulletSize));
            if (rightBullet->GetBullet())
            {
                rightBullet->GetBullet()->setVisible(false);
            }
            // Bullet visibility
            leftBullet->GetBullet()->setVisible(true);
            rightBullet->GetBullet()->setVisible(true);
            // Push bullets to active bullets list
            activeBullets.push_back(leftBullet);
            activeBullets.push_back(rightBullet);
        }
        if (rapidFireTimer > 0 && splitFireTimer > 0)
        {
            Bullet* leftBullet = pool->GetResource();
            Bullet* rightBullet = pool->GetResource();
            bullet->SetBulletMode(Bullet::BulletMode::rapidFire);
            leftBullet->SetBulletMode(Bullet::BulletMode::rapidSplitFire);
            rightBullet->SetBulletMode(Bullet::BulletMode::rapidSplitFire);
            leftBullet->SetBulletSpread(-0.1f);
            rightBullet->SetBulletSpread(0.1f);
            
            // Left bullet for split fire
            leftBullet->SetBullet(playerSmgr->addCubeSceneNode(10.f, 0, -1,
      playerObject->getPosition(), playerObject->getRotation(),
      bulletSize));
            if (leftBullet->GetBullet())
            {
                leftBullet->GetBullet()->setVisible(false);
            }
            // Right bullet for split fire
            rightBullet->SetBullet(playerSmgr->addCubeSceneNode(10.f, 0, -1,
      playerObject->getPosition(), playerObject->getRotation(),
      bulletSize));
            if (rightBullet->GetBullet())
            {
                rightBullet->GetBullet()->setVisible(false);
            }
            // Bullet visibility
            leftBullet->GetBullet()->setVisible(true);
            rightBullet->GetBullet()->setVisible(true);
            // Push bullets to active bullets list
            activeBullets.push_back(leftBullet);
            activeBullets.push_back(rightBullet);
            _Cam->state = _Cam->shootShaking;
        }
        // Push bullets to active bullets list
        activeBullets.push_back(bullet);
        hasShot = true;
        // Bullet visibility
        bullet->GetBullet()->setVisible(true);
        // Timer reset
        bulletTimer = bullet->GetBulletTimer();
    }
    if (hasShot)
    {
        if (!activeBullets.empty())
        {
            for (int i = 0; i < activeBullets.size(); i++)
            {
                activeBullets[i]->UpdateBullet(mousePosition,
      playerObject->getPosition(), frameDeltaTime);
                for (int j = 0; j < enemies->getActiveEnemies().size(); j++)
                {
                    if (playerCol.SceneNodeWithSceneNode(enemies->
      getActiveEnemies()[j]->GetEnemySceneNode(), activeBullets[i]->GetBullet()))
                    {
                        enemies->GetEnemy(j)->TakeDamage(
      activeBullets[i]->GetDamage());
                        playerScores.DisplayScore(10);
                        pool->ReturnResource(activeBullets[i]);
                        activeBullets.erase(i);
                        // return to correct the index
                        return;
                    }
                }
                // Check collision with static walls or the life time of the bullet
                if ((activeBullets[i] && playerCol.
      CollidesWithStaticObjects(activeBullets[i]->GetBullet())) ||
                    (activeBullets[i] && activeBullets[i]->GetBulletLifeTimer() =
      = 0))
                {
                    pool->ReturnResource(activeBullets[i]);
                    activeBullets.erase(i);
                }
                if (activeBullets.empty())
                {
                    hasShot = false;
                }
            }
        }
    }
}
void Player::TakeDamage (irr::f32 damage)
Take damage.
References game, gameOverState, health, playerIDevice, SoundManager::PlaySound(), Game::SetIsGameOver(), GameOverState::ShowGameOver(), soundManager, TAKE_DAMAGE_SOUND1, TAKE_DAMAGE_SOUND2, TAKE_DAMAGE_SOUND3, TAKE_DAMAGE_SOUND4, VULNERABLE_BASE_TIMER, and vulnerableTimer.
Referenced by Enemy::Attack().
{
    if (health > 0 && vulnerableTimer <= 0)
    {
        switch (rand() % 4)
        {
        case 0:
            soundManager->PlaySound(TAKE_DAMAGE_SOUND1, false);
            break;
        case 1:
            soundManager->PlaySound(TAKE_DAMAGE_SOUND2, false);
            break;
        case 2:
            soundManager->PlaySound(TAKE_DAMAGE_SOUND3, false);
            break;
        case 3:
            soundManager->PlaySound(TAKE_DAMAGE_SOUND4, false);
            break;
        }
        vulnerableTimer = VULNERABLE_BASE_TIMER;
        health -= damage;
        if (health <= 0)
        {
            gameOverState.ShowGameOver(playerIDevice);
            game->SetIsGameOver(true);
        }
    }
}
Member Data Documentation
irr::s32 Player::bulletTimer [private]
The bullet timer.
irr::s32 Player::rapidFireTimer [private]
The rapid fire power up timer.
irr::s32 Player::splitFireTimer [private]
The split fire power up timer.
The documentation for this class was generated from the following files:
Player.h
Player.cpp