BulletPool Class Reference
A bullet pool.
#include <BulletPool.h>
Public Member Functions
BulletPool (const BulletPool &)=delete
Delete copy constructor.
BulletPool & operator= (const BulletPool &)=delete
Delete assignment operator.
Bullet * GetResource ()
Gets the resource.
void ReturnResource (Bullet *object)
Returns a resource.
Static Public Member Functions
static BulletPool * GetInstance ()
Gets the instance.
Private Member Functions
BulletPool ()
Default constructor.
Private Attributes
std::list< Bullet * > resources
The resources.
Static Private Attributes
static BulletPool * instance = 0
The instance.
Detailed Description
A bullet pool.
Constructor & Destructor Documentation
BulletPool::BulletPool (const BulletPool &) [delete]
Delete copy constructor.
BulletPool::BulletPool () [private]
Default constructor.
Default constructor.
Referenced by GetInstance().
{
}
Member Function Documentation
BulletPool * BulletPool::GetInstance () [static]
Gets the instance.
References BulletPool(), and instance.
Referenced by Player::Init().
{
    if (!instance)
    {
        instance = new BulletPool();
    }
    return instance;
}
Bullet * BulletPool::GetResource ()
Gets the resource.
References resources.
Referenced by Player::Shoot().
{
    if (resources.empty())
    {
        return new Bullet();
    }
    else
    {
        Bullet* bullet = resources.front();
        resources.pop_front();
        return bullet;
    }
}
BulletPool& BulletPool::operator= (const BulletPool &) [delete]
Delete assignment operator.
void BulletPool::ReturnResource (Bullet * object)
Returns a resource.
Resets the object and returns the resource back to the resources.
References resources.
Referenced by Player::Shoot().
{
    object->Reset();
    resources.push_back(object);
}
Member Data Documentation
BulletPool * BulletPool::instance = 0 [static], [private]
The instance.
Referenced by GetInstance().
std::list<Bullet*> BulletPool::resources [private]
The resources.
Referenced by GetResource(), and ReturnResource().
The documentation for this class was generated from the following files:
BulletPool.h
BulletPool.cpp