Bullet Class Reference
#include <Bullet.h>
Public Types
enum BulletMode { basic,
rapidFire,
splitFire,
rapidSplitFire
 }
Bullet Modes.
Public Member Functions
void SetBulletMode (BulletMode mode)
Set the Bullet Mode.
void Reset ()
Resets this object.
irr::scene::ISceneNode * GetBullet ()
Gets the bullet.
void SetBullet (irr::scene::ISceneNode *newBullet)
Sets a bullet.
float GetDamage ()
Gets the damage.
void UpdateBullet (irr::core::vector3df mousePos, irr::core::vector3df playerPos, float frameDeltaTime)
Updates the bullet.
void SetSpeed (float s)
Sets the bullet speed.
irr::s32 GetBulletTimer ()
Default constructor.
irr::s32 GetBulletLifeTimer ()
void SetBulletSpread (float s)
Bullet ()
Default constructor.
Private Attributes
irr::scene::ISceneNode * bullet
The bullet.
BulletMode bulletMode
The Bullet mode.
bool setOnce = true
True to set once.
irr::core::vector3df position
The velocity.
irr::core::vector3df delta
The delta.
float speed
The speed.
float damage
The damage.
irr::s32 bulletTimer
The bullet timer.
irr::s32 bulletLifeTimer
The bullet life timer.
float spread
The bullet offset.
irr::f32 length
irr::core::vector3df perpendicular
irr::core::vector3df offPos
Detailed Description
A bullet.
Member Enumeration Documentation
enum Bullet::BulletMode
Bullet Modes.
Enumerator
basic
rapidFire
splitFire
rapidSplitFire
                    {
        basic,
        rapidFire,
        splitFire,
        rapidSplitFire
    };
Constructor & Destructor Documentation
Bullet::Bullet ()
Default constructor.
{
    bullet = 0;
    SetBulletMode(BulletMode::basic);
}
Member Function Documentation
ISceneNode * Bullet::GetBullet ()
Gets the bullet.
Referenced by Player::Shoot().
{
    return bullet;
}
s32 Bullet::GetBulletLifeTimer ()
{
    return bulletLifeTimer;
}
s32 Bullet::GetBulletTimer ()
Default constructor.
Referenced by Player::Shoot().
{
    return bulletTimer;
}
float Bullet::GetDamage ()
Gets the damage.
{
    return damage;
}
void Bullet::Reset ()
Resets this object.
{
    SetBulletMode(BulletMode::basic);
    bullet->setVisible(false);
    bullet->setPosition(vector3df(0, 0, 0));
    setOnce = true;
}
void Bullet::SetBullet (irr::scene::ISceneNode * newBullet)
Sets a bullet.
Referenced by Player::Shoot().
{
    bullet = newBullet;
}
void Bullet::SetBulletMode (BulletMode mode)
Set the Bullet Mode.
Referenced by Player::Shoot().
{
    bulletMode = mode;
    switch (mode)
    {
    case BulletMode::basic:
        speed = 300.f;
        damage = 25.f;
        bulletLifeTimer = 150;
        bulletTimer = 15;
        return;
    case BulletMode::rapidFire:
        speed = 350.f;
        bulletLifeTimer = 150;
        bulletTimer = 9;
        return;
    case BulletMode::splitFire:
        speed = 300.f;
        bulletLifeTimer = 150;
        bulletTimer = 13;
        return;
    case BulletMode::rapidSplitFire:
        speed = 300.f;
        bulletLifeTimer = 150;
        bulletTimer = 9;
    }
}
void Bullet::SetBulletSpread (float s)
Referenced by Player::Shoot().
{
    spread = s;
}
void Bullet::SetSpeed (float s)
Sets the bullet speed.
{
    speed = s;
}
void Bullet::UpdateBullet (irr::core::vector3df mousePos, irr::core::vector3df playerPos, float frameDeltaTime)
Updates the bullet.
References frameDeltaTime.
{
    if (bulletLifeTimer > 0)
    {
        bulletLifeTimer -= frameDeltaTime;
    }
    if (setOnce)
    {
        position = playerPos;
        delta = vector3df(mousePos.X - playerPos.X, 1.f, mousePos.Z - playerPos.Z);
        length = delta.getLength();
        delta = delta.normalize();
        if ((bulletMode == BulletMode::rapidSplitFire || bulletMode ==
      BulletMode::splitFire) && (spread > 0 || spread < 0))
        {
            perpendicular = vector3df(delta.Z, delta.Y,
      delta.X);
            offPos = mousePos + (perpendicular * spread *
      length);
            //recalculate delta based on offset position
            delta = vector3df(offPos.X - playerPos.X, 1.f, offPos.Z - playerPos.Z);
            delta.normalize();
        }
        setOnce = false;
    }
    position += delta * frameDeltaTime * speed;
    position.Y = 1.f;
    bullet->setPosition(position);
}
Member Data Documentation
irr::scene::ISceneNode* Bullet::bullet [private]
The bullet.
irr::s32 Bullet::bulletLifeTimer [private]
The bullet life timer.
BulletMode Bullet::bulletMode [private]
The Bullet mode.
irr::s32 Bullet::bulletTimer [private]
The bullet timer.
float Bullet::damage [private]
The damage.
irr::core::vector3df Bullet::delta [private]
The delta.
irr::f32 Bullet::length [private]
irr::core::vector3df Bullet::offPos [private]
irr::core::vector3df Bullet::perpendicular [private]
irr::core::vector3df Bullet::position [private]
The velocity.
bool Bullet::setOnce = true [private]
True to set once.
float Bullet::speed [private]
The speed.
float Bullet::spread [private]
The bullet offset.
The documentation for this class was generated from the following files:
Bullet.h
Bullet.cpp