Collision Class Reference
#include <Collision.h>
Public Member Functions
void AddWallToList (irr::scene::ISceneNode *wall)
void AddStaticToList (irr::scene::ISceneNode *staticObject)
void AddDynamicToList (irr::scene::ISceneNode *dynamicObject)
void RemoveDynamicFromList (irr::scene::ISceneNode *dynamicObject)
void AddPowerupToList (Powerup *powerup)
bool SceneNodeWithSceneNode (irr::scene::ISceneNode *tBox1, irr::scene::ISceneNode *tBox2)
bool CollidesWithStaticObjects (irr::scene::ISceneNode *dynamicObject)
void DiscreteCollisionUpdate (irr::f32 frameDeltaTime)
Powerup * CollidesWithPowerup (irr::scene::ISceneNode *player)
Member Function Documentation
void Collision::AddDynamicToList (irr::scene::ISceneNode * dynamicObject)
References dynamicList.
Referenced by Player::Init(), EnemySpawner::Spawn(), and EnemySpawner::SpawnMathroskaMinion().
{ dynamicList.push_back(dynamicObject); }
void Collision::AddPowerupToList (Powerup * powerup)
References powerupList.
Referenced by PowerUpSpawner::PowerUpSpawn().
{ powerupList.push_back(powerup); }
void Collision::AddStaticToList (irr::scene::ISceneNode * staticObject)
References staticList.
Referenced by ObjectPlacementGeneration::CreateObjects().
{ staticList.push_back(staticObject); }
void Collision::AddWallToList (irr::scene::ISceneNode * wall)
References wallList.
Referenced by ObjectPlacementGeneration::CreateDefaultObjects().
{ wallList.push_back(wall); }
Powerup * Collision::CollidesWithPowerup (irr::scene::ISceneNode * player)
References powerupList.
Referenced by Player::Move().
{
    for (u32 i = 0; i < powerupList.size(); i++)
        if (SceneNodeWithSceneNode(player,
      powerupList[i]->GetNode()))
        {
            Powerup* pow = powerupList[i];
            powerupList.erase(i);
            return pow;
        }
    return false;
}
bool Collision::CollidesWithStaticObjects (irr::scene::ISceneNode * dynamicObject)
References staticList.
Referenced by Player::Move(), and Player::Shoot().
{
    for (u32 i = 0; i < staticList.size(); i++)
    {
        if (SceneNodeWithSceneNode(dynamicObject,
      staticList[i]))
        {
            return true;
        }
    }
    return false;
}
void Collision::DiscreteCollisionUpdate (irr::f32 frameDeltaTime)
References dynamicList, frameDeltaTime, staticList, and wallList.
Referenced by Game::Update().
{
    vector3df difference, seperation;
    //for all dynamic objects
    for (u32 i = 0; i < dynamicList.size(); i++)
    {
        vector3df colliderExtent = dynamicList[i]->getBoundingBox().getExtent() / 2;
        vector3df colliderPos = dynamicList[i]->getPosition();
        //for all dynamic objects,...
        for (u32 j = i + 1; j < dynamicList.size(); j++)
        {
            if (j > dynamicList.size())
                break;
            //if one overlaps the other
            if (SceneNodeWithSceneNode(dynamicList[i],
      dynamicList[j]))
            {
                //solve interpenetration
                vector3df dynamicPos = dynamicList[j]->getPosition();
                vector3df dynamicExtent = dynamicList[j]->getBoundingBox().getExtent() / 2;
                vector3df center;
                if (colliderPos == dynamicPos) //if they are on top of eachother
                    center = colliderPos + vector3df(1, 0, 1); //seperate at a random vector
                else
                    center = (colliderPos + dynamicPos) / 2; //average of both positions
                difference = center - colliderPos;
                seperation = difference.normalize() * (colliderExtent.getLength() + dynamicExtent.getLength
      ())* frameDeltaTime;
                seperation.Y = 0;
                //dissect Y, so it does not average all object heights
                dynamicList[j]->setPosition(dynamicPos + (seperation));
            }
        }
        //...AND static objects
        for (u32 j = 0; j < staticList.size(); j++)
        {
            //if one overlaps the other
            if (SceneNodeWithSceneNode(dynamicList[i],
      staticList[j]))
            {
                //solve interpenetration
                vector3df staticExtent = staticList[j]->getBoundingBox().getExtent() / 2;
                vector3df staticPos = staticList[j]->getPosition();
                difference = colliderPos - staticPos;
                seperation = difference.normalize() * (colliderExtent.getLength() + staticExtent.getLength(
      )) / 20;
                seperation.Y = 0;
                dynamicList[i]->setPosition(colliderPos + seperation);
            }
        }
        for (u32 j = 0; j < wallList.size(); j++)
        {
            //if one overlaps the other
            if (SceneNodeWithSceneNode(dynamicList[i],
      wallList[j]))
            {
                switch (j) {
                case 0: // left wall
                    seperation = vector3df(0, 0, -100) * frameDeltaTime;
                    dynamicList[i]->setPosition(colliderPos + seperation);
                    break;
                case 1: // top wall
                    seperation = vector3df(-100, 0, 0) * frameDeltaTime;
                    dynamicList[i]->setPosition(colliderPos + seperation);
                    break;
                case 2: // right wall
                    seperation = vector3df(0, 0, 100) * frameDeltaTime;
                    dynamicList[i]->setPosition(colliderPos + seperation);
                    break;
                case 3: // bottom wall
                    seperation = vector3df(100, 0, 0) * frameDeltaTime;
                    dynamicList[i]->setPosition(colliderPos + seperation);
                    break;
                }
            }
        }
    }
}
void Collision::RemoveDynamicFromList (irr::scene::ISceneNode * dynamicObject)
References dynamicList.
Referenced by EnemySpawner::UpdateEnemies().
{
    for (int i = 0; i < dynamicList.size(); i++)
        if (dynamicList[i] == dynamicObject)
        {
            dynamicList.erase(i);
            break;
        }
}
bool Collision::SceneNodeWithSceneNode (irr::scene::ISceneNode * tBox1, irr::scene::ISceneNode * tBox2)
Referenced by Player::Shoot().
{
    return(tBox1->getTransformedBoundingBox().intersectsWithBox(tBox2->getTransformedBoundingBox()));
}
The documentation for this class was generated from the following files:
Collision.h
Collision.cpp