EnemyPool Class Reference
#include <EnemyPool.h>
Public Member Functions
EnemyPool (const EnemyPool &)=delete
EnemyPool & operator= (const EnemyPool &)=delete
Enemy * GetResource ()
void ReturnResource (Enemy *object)
Static Public Member Functions
static EnemyPool * GetInstance (irr::IrrlichtDevice *device)
Private Member Functions
EnemyPool (irr::IrrlichtDevice *device)
Private Attributes
std::list< Enemy * > resources
Static Private Attributes
static EnemyPool * instance = 0
Constructor & Destructor Documentation
EnemyPool::EnemyPool (const EnemyPool &) [delete]
Referenced by GetInstance().
EnemyPool::EnemyPool (irr::IrrlichtDevice * device) [private]
References EnemyPoolDevice.
{
    EnemyPoolDevice = device;
}
Member Function Documentation
EnemyPool * EnemyPool::GetInstance (irr::IrrlichtDevice * device) [static]
References EnemyPool(), and instance.
Referenced by EnemySpawner::EnemySpawner().
{
    if (!instance)
    {
        instance = new EnemyPool(device);
    }
    return instance;
}
Enemy * EnemyPool::GetResource ()
References enemy, EnemyPoolDevice, Enemy::GetEnemySceneNode(), and resources.
Referenced by EnemySpawner::Spawn(), and EnemySpawner::SpawnMathroskaMinion().
{
    if (resources.empty())
    {
        Enemy* enemy = new Enemy(EnemyPoolDevice);
        return enemy;
    }
    else
    {
        Enemy* enemy = resources.front();
        resources.pop_front();
        enemy->GetEnemySceneNode()->setVisible(true);
        return enemy;
    }
}
EnemyPool& EnemyPool::operator= (const EnemyPool &) [delete]
void EnemyPool::ReturnResource (Enemy * object)
References resources.
Referenced by EnemySpawner::UpdateEnemies().
{
    object->Reset();
    resources.push_back(object);
}
Member Data Documentation
EnemyPool * EnemyPool::instance = 0 [static], [private]
Referenced by GetInstance().
std::list<Enemy*> EnemyPool::resources [private]
Referenced by GetResource(), and ReturnResource().
The documentation for this class was generated from the following files:
EnemyPool.h
EnemyPool.cpp