Game Class Reference
#include <Game.h>
Public Member Functions
Game (const Game &)=delete
Game & operator= (const Game &)=delete
bool GetIsGameOver ()
bool SetIsGameOver (bool state)
void Start ()
void Update ()
void Draw ()
Player * GetPlayer ()
Static Public Member Functions
static Game * GetInstance ()
Public Attributes
irr::IrrlichtDevice * device
ObjectPlacementGeneration objectPlacementGen
Private Member Functions
Game ()
Private Attributes
bool isGameOver = false
Player * player
Static Private Attributes
static Game * instance = 0
Constructor & Destructor Documentation
Game::Game (const Game &) [delete]
Game::Game () [private]
References inputReceiver.
{
    // Create device
    device = createDevice(EDT_DIRECT3D9,
        dimension2d<u32>(800, 600), 16, false, false, true, &inputReceiver);
}
Member Function Documentation
void Game::Draw ()
References Player::DrawHealthBar(), driver, guienv, lastFPS, player, score, Score::Scoring(), smgr, uISystem, and UISystem::WaveUI().
Referenced by main().
{
    driver->beginScene(true, true, SColor(255, 113, 113, 133));
    smgr->drawAll();
    guienv->drawAll();
    player->DrawHealthBar();
    score.Scoring(device);
    uISystem->WaveUI(device);
    driver->endScene();
    int fps = driver->getFPS();
    if (lastFPS != fps)
    {
        stringw tmp(L"KOMMANDOS - Irrlicht Engine");
        tmp += driver->getName();
        tmp += L"] fps: ";
        tmp += fps;
        device->setWindowCaption(tmp.c_str());
        lastFPS = fps;
    }
}
Game * Game::GetInstance () [static]
Referenced by Camera::Camera(), EnemySpawner::EnemySpawner(), ObjectPlacementGeneration::GenerateNewObjects(), UISystem::InitUISystem(), main(), Player::Player(), Score::Scoring(), and UISystem::UISystem().
                        {
    if (!instance)
    {
        instance = new Game();
    }
    return instance;
}
bool Game::GetIsGameOver ()
References isGameOver.
Referenced by Player::DrawHealthBar(), Score::Scoring(), EnemySpawner::UpdateEnemies(), and UISystem::WaveUI().
                         {
    return isGameOver;
}
Player * Game::GetPlayer ()
References player.
Referenced by UISystem::InitUISystem().
{
    return player;
}
Game& Game::operator= (const Game &) [delete]
bool Game::SetIsGameOver (bool state)
References camera, Camera::gameover, isGameOver, Tutorial::RemoveTutorial(), Camera::state, and tutorial.
Referenced by Player::TakeDamage().
{
    tutorial.RemoveTutorial();
    camera->state = camera->gameover;
    return isGameOver = state;
}
void Game::Start ()
References camera, driver, enemySpawner, SoundManager::GetInstance(), Camera::GetInstance(), guienv, UISystem::InitUISystem(), player, SoundManager::PlaySound(), powerSpawn, PowerUpSpawner::PowerUpDevice(), prevFrame, score, Score::Scoring(), Tutorial::ShowTutorial(), smgr, soundManager, tutorial, and uISystem.
Referenced by main().
{
    //Get the sound engine
    SoundManager* soundManager = soundManager->
      GetInstance();
    //Start Game Background song
    soundManager->PlaySound("../media/Sounds/bgsound.mp3", true);
    // Create instances of classes
    camera = camera->GetInstance(device);
    player = new Player(device);
    enemySpawner = new EnemySpawner(device, player);
    uISystem = new UISystem(device);
    //score.Scoring is unneeded duplicate code
    score.Scoring(device);
    tutorial.ShowTutorial(device);
    driver = device->getVideoDriver();
    smgr = device->getSceneManager();
    guienv = device->getGUIEnvironment();
    objectPlacementGen.PlaceObjects(device);
    powerSpawn->PowerUpDevice(device);
    uISystem->InitUISystem(device);
    //Create Light
    ILightSceneNode* directionalLight = device->getSceneManager()->addLightSceneNode();
    SLight & lightData = directionalLight->getLightData();
    lightData.Type = ELT_DIRECTIONAL;
    directionalLight->setRotation(vector3df(90, 0, 0));
    device->getCursorControl()->setVisible(true);
    //This is used to calculate frame delta time
    prevFrame = device->getTimer()->getTime();
}
void Game::Update ()
References camera, Camera::CameraUpdate(), collisionManager, Collision::DiscreteCollisionUpdate(), enemySpawner, frameDeltaTime, inputReceiver, isGameOver, Tutorial::isTutorialActive, Player::Move(), player, prevFrame, Player::Shoot(), tutorial, Tutorial::Update(), and EnemySpawner::UpdateEnemies().
Referenced by main().
{
    // Work out a frame delta time.
    const u32 currentFrame = device->getTimer()->getTime();
    const f32 frameDeltaTime = (f32)(currentFrame - prevFrame) / 1000.f; // Time in
       seconds
    prevFrame = currentFrame;
    camera->CameraUpdate(frameDeltaTime);
    if (tutorial.isTutorialActive) {
        tutorial.Update(frameDeltaTime);
    }
    if (!isGameOver)
    {
        player->Move(inputReceiver);
        player->Shoot(inputReceiver, enemySpawner);
        if(!tutorial.isTutorialActive)
            enemySpawner->UpdateEnemies();
        collisionManager.DiscreteCollisionUpdate(frameDeltaTime);
    }
}
Member Data Documentation
irr::IrrlichtDevice* Game::device
Referenced by HeatMapManager::CreateDangerZone(), HeatMapManager::CreatePoisonCloud(), ObjectPlacementGeneration::GenerateNewObjects(), UISystem::InitUISystem(), and main().
Game * Game::instance = 0 [static], [private]
bool Game::isGameOver = false [private]
ObjectPlacementGeneration Game::objectPlacementGen
Referenced by HeatMapManager::Update().
Player* Game::player [private]
The documentation for this class was generated from the following files:
Game.h
Game.cpp