Score Class Reference
#include <Score.h>
Public Member Functions
void Scoring (irr::IrrlichtDevice *device)
void DisplayScore (irr::f32 points)
Member Function Documentation
void Score::DisplayScore (irr::f32 points)
References score.
Referenced by Player::Shoot().
{
    score += points;
}
void Score::Scoring (irr::IrrlichtDevice * device)
References font2, game_Score, Game::GetInstance(), Game::GetIsGameOver(), score, scoreGui, and timer.
Referenced by Game::Draw(), and Game::Start().
{
    game_Score = game_Score->GetInstance();
    scoreGui = device->getGUIEnvironment();
    timer = device->getTimer()->getTime();
    font2 = device->getGUIEnvironment()->getFont("../media/Fonts/fontlucida.png");
    core::stringw scoreString = L"Score: ";
    scoreString += score;
    if (game_Score->GetIsGameOver() != true)
    {
    font2->draw(stringw(scoreString).c_str(),
        core::rect<s32>(80, 40, 200, 100),
        video::SColor(255, 255, 255, 255));
    DisplayScore(0);
    }
}
The documentation for this class was generated from the following files:
Score.h
Score.cpp