Camera Class Reference
Top down camera that follows player
#include <Camera.h>
Public Types
enum CameraState {
*
normal,
waveShaking,
bigWaveShaking,
shootShaking,
*
gameover
 }
Public Member Functions
Camera (irr::IrrlichtDevice *device)
Constructor.
void CameraUpdate (f32 frameDeltaTime)
Updates the camera position and target
Static Public Member Functions
static Camera * GetInstance (IrrlichtDevice *device)
Public Attributes
CameraState state
Private Member Functions
void CameraInit ()
Initialization of the Camera
void ScreenShake (f32 frameDeltaTim, f32 intensity)
Static Private Attributes
static Camera * instance = 0
Initializes the camera
Detailed Description
Top down camera that follows player
Member Enumeration Documentation
enum Camera::CameraState
Enumerator
normal
waveShaking
bigWaveShaking
shootShaking
gameover
    {
        normal,
        waveShaking,
        bigWaveShaking,
        shootShaking,
        gameover
    };
Constructor & Destructor Documentation
Camera::Camera (irr::IrrlichtDevice * device)
Constructor.
References _soundManager, cameraIDevice, cameraSmgr, game_, Game::GetInstance(), and SoundManager::GetInstance().
{
    cameraIDevice = device;
    cameraSmgr = cameraIDevice->getSceneManager();
    game_ = game_->GetInstance();
    CameraInit();
    _soundManager = _soundManager->GetInstance();
}
Member Function Documentation
void Camera::CameraInit () [private]
Initialization of the Camera
References camera, cameraSmgr, cameraStartPosition, cameraStartTarget, newCameraPosition, and time.
{
    camera = cameraSmgr->addCameraSceneNode();
    if (camera)
    {
        camera->setPosition(cameraStartPosition);
        camera->setTarget(cameraStartTarget);
        newCameraPosition.Y = 80;
    }
    //shakeTimer = maxTime;
    srand(time(0));
    state = normal;
}
void Camera::CameraUpdate (f32 frameDeltaTime)
Updates the camera position and target
Update camera position relative to the player while game is playing and move camera to start pos when game is over
References _soundManager, camera, cameraStartPosition, cameraStartTarget, EARTHQUAKE_SOUND, Player::getPlayerObject(), isShaking, maxTimeNormalShake, newCameraPosition, player_, SoundManager::PlaySound(), shakeTimer, shotTimeShake, and soundPlaying.
Referenced by Game::Update().
{
    switch (state)
    {
    case normal:
        if (camera)
        {
            newCameraPosition.X = player_->
      getPlayerObject()->getPosition().X;
            newCameraPosition.Z = player_->
      getPlayerObject()->getPosition().Z;
            camera->setPosition(newCameraPosition);
            camera->setTarget(player_->getPlayerObject()->getPosition());
        }
        soundPlaying = false;
        isShaking = false;
        break;
    case waveShaking:
        if (!isShaking)
        {
            isShaking = true;
            shakeTimer = maxTimeNormalShake;
        }
        ScreenShake(frameDeltaTime, 0.4);
        if (!soundPlaying)
        {
            soundPlaying = true;
            _soundManager->PlaySound(EARTHQUAKE_SOUND, false);
        }
        break;
    case bigWaveShaking:
        if (!isShaking)
        {
            isShaking = true;
            shakeTimer = maxTimeNormalShake;
        }
        ScreenShake(frameDeltaTime, 0.5);
        if (!soundPlaying)
        {
            soundPlaying = true;
            _soundManager->PlaySound(EARTHQUAKE_SOUND, false);
        }
        break;
    case shootShaking:
        if (!isShaking)
        {
            isShaking = true;
            shakeTimer = shotTimeShake;
        }
        ScreenShake(frameDeltaTime, 2);
        break;
    case gameover:
        camera->setPosition(cameraStartPosition);
        camera->setTarget(cameraStartTarget);
        break;
    }
}
Camera * Camera::GetInstance (IrrlichtDevice * device) [static]
Referenced by EnemySpawner::EnemySpawner(), Player::Init(), and Game::Start().
{
    if (!instance)
    {
        instance = new Camera(device);
    }
    return instance;
}
void Camera::ScreenShake (f32 frameDeltaTim, f32 intensity) [private]
References camera, frameDeltaTime, Player::getCamFollowObject(), Player::getPlayerObject(), newCameraPosition, player_, resetTime, and shakeTimer.
{
    if (shakeTimer > 0)
    {
        shakeTimer -= frameDeltaTime;
        resetTime += frameDeltaTime;
        
        const f32 dur = 0.6;
        
        vector3df playerPos = player_->getPlayerObject()->getPosition();
        vector3df randomVec = vector3df(playerPos.X + rand() % 2 * intensity, playerPos.Y, playerPos.Z +
      rand() % 2 * intensity);
        
        if (resetTime <= dur)
        {
            player_->getCamFollowObject()->setPosition(randomVec);
            camera->setTarget(player_->getCamFollowObject()->getPosition());
            newCameraPosition.X = player_->
      getCamFollowObject()->getPosition().X;
            newCameraPosition.Z = player_->
      getCamFollowObject()->getPosition().Z;
            camera->setPosition(newCameraPosition);
        }
        if (resetTime > dur)
        {
            player_->getCamFollowObject()->setPosition(randomVec);
            camera->setTarget(player_->getCamFollowObject()->getPosition());
            newCameraPosition.X = player_->
      getCamFollowObject()->getPosition().X;
            newCameraPosition.Z = player_->
      getCamFollowObject()->getPosition().Z;
            camera->setPosition(newCameraPosition);
        }
        if (resetTime > dur * 2)
        {
            resetTime = 0;
        }
    }
    else
    {
        //shakeTimer = maxTime;
        state = normal;
    }
}
Member Data Documentation
Camera * Camera::instance = 0 [static], [private]
Initializes the camera
Constructor.
CameraState Camera::state
Referenced by EnemySpawner::NextWave(), Game::SetIsGameOver(), and Player::Shoot().
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp