Catch::Detail::Approx Class Reference
#include <catch.hpp>
Public Member Functions
Approx (double value)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
Approx operator() (T const &value)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
Approx (T const &value)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
Approx & epsilon (T const &newEpsilon)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
Approx & margin (T const &newMargin)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
Approx & scale (T const &newScale)
std::string toString () const
Static Public Member Functions
static Approx custom ()
Private Member Functions
bool equalityComparisonImpl (double other) const
Private Attributes
double m_epsilon
double m_margin
double m_scale
double m_value
Friends
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator== (const T &lhs, Approx const &rhs)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator== (Approx const &lhs, const T &rhs)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator!= (T const &lhs, Approx const &rhs)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator!= (Approx const &lhs, T const &rhs)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator<= (T const &lhs, Approx const &rhs)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator<= (Approx const &lhs, T const &rhs)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator>= (T const &lhs, Approx const &rhs)
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type>
bool operator>= (Approx const &lhs, T const &rhs)
Constructor & Destructor Documentation
Catch::Detail::Approx::Approx (double value) [explicit]
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> Catch::Detail::Approx::Approx (T const & value) [inline], [explicit]
                                            : Approx(static_cast<double>(value))
            {}
Member Function Documentation
static Approx Catch::Detail::Approx::custom () [static]
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> Approx& Catch::Detail::Approx::epsilon (T const & newEpsilon) [inline]
References Catch::Detail::stringify().
Referenced by operator()().
                                                 {
                double epsilonAsDouble = static_cast<double>(newEpsilon);
                if (epsilonAsDouble < 0 || epsilonAsDouble > 1.0) {
                    throw std::domain_error
                    ("Invalid Approx::epsilon: " +
                        Catch::Detail::stringify(epsilonAsDouble) +
                        ", Approx::epsilon has to be between 0 and 1");
                }
                m_epsilon = epsilonAsDouble;
                return *this;
            }
bool Catch::Detail::Approx::equalityComparisonImpl (double other) const [private]
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> Approx& Catch::Detail::Approx::margin (T const & newMargin) [inline]
References Catch::Detail::stringify().
Referenced by operator()().
                                               {
                double marginAsDouble = static_cast<double>(newMargin);
                if (marginAsDouble < 0) {
                    throw std::domain_error
                    ("Invalid Approx::margin: " +
                        Catch::Detail::stringify(marginAsDouble) +
                        ", Approx::Margin has to be non-negative.");
                }
                m_margin = marginAsDouble;
                return *this;
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> Approx Catch::Detail::Approx::operator() (T const & value) [inline]
References epsilon(), margin(), and scale().
                                              {
                Approx approx(static_cast<double>(value));
                approx.epsilon(m_epsilon);
                approx.margin(m_margin);
                approx.scale(m_scale);
                return approx;
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> Approx& Catch::Detail::Approx::scale (T const & newScale) [inline]
Referenced by operator()().
                                             {
                m_scale = static_cast<double>(newScale);
                return *this;
            }
std::string Catch::Detail::Approx::toString () const
Friends And Related Function Documentation
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator!= (T const & lhs, Approx const & rhs) [friend]
                                                                      {
                return !operator==(lhs, rhs);
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator!= (Approx const & lhs, T const & rhs) [friend]
                                                                      {
                return !operator==(rhs, lhs);
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator<= (T const & lhs, Approx const & rhs) [friend]
                                                                      {
                return static_cast<double>(lhs) < rhs.m_value || lhs == rhs;
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator<= (Approx const & lhs, T const & rhs) [friend]
                                                                      {
                return lhs.m_value < static_cast<double>(rhs) || lhs == rhs;
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator== (const T & lhs, Approx const & rhs) [friend]
                                                                      {
                auto lhs_v = static_cast<double>(lhs);
                return rhs.equalityComparisonImpl(lhs_v);
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator== (Approx const & lhs, const T & rhs) [friend]
                                                                      {
                return operator==(rhs, lhs);
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator>= (T const & lhs, Approx const & rhs) [friend]
                                                                      {
                return static_cast<double>(lhs) > rhs.m_value || lhs == rhs;
            }
template<typename T , typename = typename std::enable_if<std::is_constructible<double, T>::value>::type> bool operator>= (Approx const & lhs, T const & rhs) [friend]
                                                                      {
                return lhs.m_value > static_cast<double>(rhs) || lhs == rhs;
            }
Member Data Documentation
double Catch::Detail::Approx::m_epsilon [private]
double Catch::Detail::Approx::m_margin [private]
double Catch::Detail::Approx::m_scale [private]
double Catch::Detail::Approx::m_value [private]
The documentation for this class was generated from the following file:
catch.hpp