PowerUpSpawner Class Reference
#include <PowerUpSpawner.h>
Public Member Functions
void PowerUpDevice (irr::IrrlichtDevice *device)
void PowerUpSpawn (vector3df position)
Public Attributes
bool pickUpPower = false
IMeshSceneNode * powerupNode
Member Function Documentation
void PowerUpSpawner::PowerUpDevice (irr::IrrlichtDevice * device)
References PowerupPool::GetInstance(), pool, powerUpDriver, powerUpIDevice, and powerUpSmgr.
Referenced by Game::Start().
{
    powerUpIDevice = device;
    powerUpSmgr = device->getSceneManager();
    powerUpDriver = device->getVideoDriver();
    pool = pool->GetInstance(powerUpIDevice);
}
void PowerUpSpawner::PowerUpSpawn (vector3df position)
References Collision::AddPowerupToList(), PowerupPool::GetResource(), pool, powCol, powerup, powerUpChance, powerUpSmgr, Powerup::SetPowerup(), and Powerup::SetPowerupType().
Referenced by EnemySpawner::UpdateEnemies().
{
    powerUpChance = rand() % 100;
    if (powerUpChance >= 80)
    {
        int powTyp = rand() % 3;
        powerup = pool->GetResource();
        powCol.AddPowerupToList(powerup);
        IMeshSceneNode* powerupNode = powerUpSmgr->addCubeSceneNode(10.0f,0,-1,
            powerUpPosition,
            vector3df(0,0,0),
            vector3df(0.4f,0.4f,0.4f));
        if (powerupNode)
        {
            powerupNode->setMaterialFlag(video::EMF_LIGHTING, false);
            //powerupNode->setMaterialTexture(0,
       powerUpDriver->getTexture("../media/Textures/powerup_firerate.png"));
            powerupNode->setVisible(true);
        }
        powerup->SetPowerup(powerupNode);
        powerup->SetPowerupType(powTyp);
    }
}
Member Data Documentation
bool PowerUpSpawner::pickUpPower = false
IMeshSceneNode* PowerUpSpawner::powerupNode
The documentation for this class was generated from the following files:
PowerUpSpawner.h
PowerUpSpawner.cpp