HeatMapManager Class Reference
#include <HeatMapManager.h>
Public Types
enum Zone {
*
Zone0,
Zone1,
Zone2,
Zone3,
*
Zone4
 }
Public Member Functions
HeatMapManager (const HeatMapManager &)=delete
HeatMapManager & operator= (const HeatMapManager &)=delete
void AddWeight (Zone zone, float weight)
int GetWeight (Zone zone)
Zone CheckZoneFromPosition (irr::core::vector3df pos)
void Update ()
irr::scene::ISceneNode * GetPoisonCloud ()
irr::scene::ISceneNode * GetDangerZone ()
Static Public Member Functions
static HeatMapManager * GetInstance ()
Public Attributes
irr::scene::IMeshSceneNode * level
Zone activeZone
bool isPoisonCloudActive = false
bool isDangerZoneActive = false
bool dangerZoneSpawned = false
Private Member Functions
HeatMapManager ()
void CreateDangerZone (Zone zone)
void CreatePoisonCloud (Zone zone)
void CreateCountdown (Zone zone)
Private Attributes
float zone1Weight
float zone2Weight
float zone3Weight
float zone4Weight
bool isZoneActive = false
bool countdown = false
float seconds
irr::scene::ISceneNode * poisonCloud
irr::scene::ISceneNode * dangerZone
irr::gui::IGUIStaticText * countdownText
Static Private Attributes
static HeatMapManager * instance = 0
Member Enumeration Documentation
enum HeatMapManager::Zone
Enumerator
Zone0
Zone1
Zone2
Zone3
Zone4
    {
        Zone0,//No Zone
        Zone1,//Left-Top
        Zone2,//Right-Top
        Zone3,//Left-Bot
        Zone4//Right-Bot
    };
Constructor & Destructor Documentation
HeatMapManager::HeatMapManager (const HeatMapManager &) [delete]
HeatMapManager::HeatMapManager () [private]
References SoundManager::GetInstance(), and hSoundManager.
{
    zone1Weight = 0;
    zone2Weight = 0;
    zone3Weight = 0;
    zone4Weight = 0;
    hSoundManager = hSoundManager->GetInstance();
}
Member Function Documentation
void HeatMapManager::AddWeight (Zone zone, float weight)
References MAX_WEIGHT.
Referenced by Player::Move(), and EnemySpawner::UpdateEnemies().
{
    if (isZoneActive) {
        return;
    }
    switch (zone)
    {
    case Zone1:
        if (zone1Weight < MAX_WEIGHT)
        {
            zone1Weight += weight;
        }
        else
        {
            CreateCountdown(Zone1);
            zone1Weight = 0;
        }
        break;
    case Zone2:
        if (zone2Weight < MAX_WEIGHT)
        {
            zone2Weight += weight;
        }
        else
        {
            CreateCountdown(Zone2);
            zone2Weight = 0;
        }
        break;
    case Zone3:
        if (zone3Weight < MAX_WEIGHT)
        {
            zone3Weight += weight;
        }
        else
        {
            CreateCountdown(Zone3);
            zone3Weight = 0;
        }
        break;
    case Zone4:
        if (zone4Weight < MAX_WEIGHT)
        {
            zone4Weight += weight;
        }
        else
        {
            CreateCountdown(Zone4);
            zone4Weight = 0;
        }
        break;
    default:
        break;
    }
}
HeatMapManager::Zone HeatMapManager::CheckZoneFromPosition (irr::core::vector3df pos)
Referenced by Player::Move(), and EnemySpawner::UpdateEnemies().
{
    if (pos.X > 0 && pos.Z > 0)
    {
        return Zone1;
    }
    else if (pos.X > 0 && pos.Z < 0)
    {
        return Zone2;
    }
    else if (pos.X < 0 && pos.Z > 0)
    {
        return Zone3;
    }
    else if (pos.X < 0 && pos.Z < 0)
    {
        return Zone4;
    }
}
void HeatMapManager::CreateCountdown (Zone zone) [private]
References MAX_COUNTDOWN_SECONDS, and ui.
{
    isZoneActive = true;
    countdown = true;
    activeZone = zone;
    stringw text("There will be gas in Zone ");
    text += zone;
    text += " in 5 seconds";
    countdownText = ui->addStaticText(text.c_str(), rect<int>(350, 80, 450, 120), true, true
      , 0, -1, true);
    countdownText->setMinSize(dimension2du(100, 40));
    countdownText->setMaxSize(dimension2du(100, 40));
    seconds = MAX_COUNTDOWN_SECONDS;
}
void HeatMapManager::CreateDangerZone (Zone zone) [private]
References Game::device, hGame, and hsmgr.
{
    const path texturePathDangerZone = "../media/Textures/danger_texture.png";
    vector3df dangerZonePosition;
    dangerZonePosition.Y = -1.5;
    f32 size = level->getTransformedBoundingBox().getExtent().X / 18;
    switch (zone)
    {
    case Zone1:
        dangerZonePosition.X = size;
        dangerZonePosition.Z = size;
        break;
    case Zone2:
        dangerZonePosition.X = size;
        dangerZonePosition.Z = -size;
        break;
    case Zone3:
        dangerZonePosition.X = -size;
        dangerZonePosition.Z = size;
        break;
    case Zone4:
        dangerZonePosition.X = -size;
        dangerZonePosition.Z = -size;
        break;
    default:
        break;
    }
    dangerZonePosition.X *= 5;
    dangerZonePosition.Z *= 5;
    dangerZone = hsmgr->addCubeSceneNode();
    if (dangerZone) {
        dangerZone->setPosition(dangerZonePosition);
        dangerZone->setScale(vector3df(size, 0.4f, size));
        dangerZone->setMaterialFlag(video::EMF_LIGHTING, false);
        dangerZone->setMaterialFlag(video::EMF_ZWRITE_ENABLE, false);
        dangerZone->setMaterialTexture(0, hGame->device->getVideoDriver()->getTexture(
      texturePathDangerZone));
        dangerZone->setMaterialType(video::EMT_TRANSPARENT_ADD_COLOR);
    }
    //isDangerZoneActive = true;
}
void HeatMapManager::CreatePoisonCloud (Zone zone) [private]
References Game::device, GAS_SOUND, hGame, hsmgr, hSoundManager, MAX_POISONCLOUS_SECONDS, and SoundManager::PlaySound().
{
    //const path texturePathDangerZone = "../media/Textures/danger_texture.png";
    const path texturePath = "../media/Textures/PoisonCloud.jpg";
    vector3df cloudPosition;
    cloudPosition.Y = -0.5;
    f32 size = level->getTransformedBoundingBox().getExtent().X / 18;
    switch (zone)
    {
    case Zone1:
        cloudPosition.X = size;
        cloudPosition.Z = size;
        break;
    case Zone2:
        cloudPosition.X = size;
        cloudPosition.Z = -size;
        break;
    case Zone3:
        cloudPosition.X = -size;
        cloudPosition.Z = size;
        break;
    case Zone4:
        cloudPosition.X = -size;
        cloudPosition.Z = -size;
        break;
    default:
        break;
    }
    cloudPosition.X *= 5;
    cloudPosition.Z *= 5;
    poisonCloud = hsmgr->addCubeSceneNode();
    if (poisonCloud) {
        poisonCloud->setPosition(cloudPosition);
        poisonCloud->setScale(vector3df(size, 4.0, size));
        poisonCloud->setMaterialFlag(video::EMF_LIGHTING, false);
        poisonCloud->setMaterialFlag(video::EMF_ZWRITE_ENABLE, false);
        poisonCloud->setMaterialTexture(0, hGame->device->getVideoDriver()->
      getTexture(texturePath));
        poisonCloud->setMaterialType(video::EMT_TRANSPARENT_ADD_COLOR);
    }
    isPoisonCloudActive = true;
    seconds = MAX_POISONCLOUS_SECONDS;
    hSoundManager->PlaySound(GAS_SOUND, false);
}
ISceneNode * HeatMapManager::GetDangerZone ()
                                          {
    return dangerZone;
}
HeatMapManager * HeatMapManager::GetInstance () [static]
Referenced by ObjectPlacementGeneration::CreateDefaultObjects(), and EnemySpawner::EnemySpawner().
{
    if (!instance)
    {
        instance = new HeatMapManager();
    }
    return instance;
}
ISceneNode * HeatMapManager::GetPoisonCloud ()
                                           {
    return poisonCloud;
}
int HeatMapManager::GetWeight (Zone zone)
{
    switch (zone)
    {
    case Zone1:
        return zone1Weight;
        break;
    case Zone2:
        return zone2Weight;
        break;
    case Zone3:
        return zone3Weight;
        break;
    case Zone4:
        return zone4Weight;
        break;
    default:
        break;
    }
}
HeatMapManager& HeatMapManager::operator= (const HeatMapManager &) [delete]
void HeatMapManager::Update ()
References ObjectPlacementGeneration::GenerateNewObjects(), hGame, hsmgr, and Game::objectPlacementGen.
Referenced by Player::Move().
{
    if (countdown)
    {
        seconds -= 0.016; //we use vsync, so it's always 60fps, 0.016 is the framedeltatime
        stringw newText("There will be gas in Zone ");
        newText += activeZone;
        newText += " in ";
        newText += seconds;
        newText += " seconds";
        countdownText->setText(newText.c_str());
        isDangerZoneActive = true;
        if (seconds < 0)
        {
            countdown = false;
            CreatePoisonCloud(activeZone);
            countdownText->remove();
        }
    }
    if (isDangerZoneActive && dangerZoneSpawned == false)
    {
        CreateDangerZone(activeZone);
        dangerZoneSpawned = true;
        //isDangerZoneActive = false;
    }
    if (isPoisonCloudActive)
    {
        if (isDangerZoneActive)
        {
            isDangerZoneActive = false;
            dangerZoneSpawned = false;
            //dangerZone->remove();
            hsmgr->addToDeletionQueue(GetDangerZone());
        }
        //hsmgr->addToDeletionQueue(GetDangerZone()); <--- HERE's THE ERROR
        seconds -= 0.016;
        if (seconds < 0)
        {
            hGame->objectPlacementGen.GenerateNewObjects(
      activeZone);
            hsmgr->addToDeletionQueue(GetPoisonCloud());
            //poisonCloud->setVisible(false);
            isZoneActive = false;
            isPoisonCloudActive = false;
            activeZone = Zone0;
        }
    }
}
Member Data Documentation
Zone HeatMapManager::activeZone
Referenced by Player::Move().
bool HeatMapManager::countdown = false [private]
irr::gui::IGUIStaticText* HeatMapManager::countdownText [private]
irr::scene::ISceneNode* HeatMapManager::dangerZone [private]
bool HeatMapManager::dangerZoneSpawned = false
HeatMapManager * HeatMapManager::instance = 0 [static], [private]
bool HeatMapManager::isDangerZoneActive = false
bool HeatMapManager::isPoisonCloudActive = false
Referenced by Player::Move().
bool HeatMapManager::isZoneActive = false [private]
irr::scene::IMeshSceneNode* HeatMapManager::level
Referenced by ObjectPlacementGeneration::CreateDefaultObjects().
irr::scene::ISceneNode* HeatMapManager::poisonCloud [private]
float HeatMapManager::seconds [private]
float HeatMapManager::zone1Weight [private]
float HeatMapManager::zone2Weight [private]
float HeatMapManager::zone3Weight [private]
float HeatMapManager::zone4Weight [private]
The documentation for this class was generated from the following files:
HeatMapManager.h
HeatMapManager.cpp